version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  api:
    build: src
    container_name: fastapi_service
    restart: always
    ports:
      - "8080:80"
