version: '3'
services:
  api:
    build: src
    container_name: fastapi_service
    restart: always
    env_file:
      - .env
    depends_on:
      - elastic
      - redis
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:8.6.2
    healthcheck:
      test: curl -f 127.0.0.1:9200 || exit 1
      interval: 10s
      timeout: 10s
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

volumes:
  elastic-data:
