version: '3'
services:
  fastapi:
    build: src
    container_name: fastapi_service
    restart: always
    env_file:
      - .env
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    expose:
      - "6379"

  elastic:
    image: elasticsearch:8.6.2
    healthcheck:
      test: curl -f 127.0.0.1:9200 || exit 1
      interval: 10s
      timeout: 10s
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    expose:
      - "9200"

volumes:
  elastic-data:
