version: '3'
services:
  elastic_dump_loader:
    image: elasticdump/elasticsearch-dump
    environment:
      - HOST=${ELASTIC_HOST}
      - PORT=${ELASTIC_PORT}
    volumes:
      - "./YA-ETL/dumps:/dumps"
      - "./load_elastic_dump.sh:/load_elastic_dump.sh"
    command: /bin/sh -c "chmod +x load_elastic_dump.sh && ./load_elastic_dump.sh"
